//! Symmetry group identification: which permutations leave the rule invariant?

use crate::agent::{AgentId, AgentState, MultiAgentUpdate, WorldState};
use std::collections::HashSet;

/// A permutation group (represented by generator permutations).
#[derive(Debug, Clone)]
pub struct SymmetryGroup {
    pub n: usize,
    /// Generator permutations as index vectors.
    pub generators: Vec<Vec<usize>>,
    pub description: String,
}

impl SymmetryGroup {
    /// Trivial group (only identity).
    pub fn trivial(n: usize) -> Self {
        Self {
            n,
            generators: vec![(0..n).collect()],
            description: format!("Trivial group on {} elements", n),
        }
    }

    /// Full symmetric group S_n (all permutations).
    pub fn full_symmetric(n: usize) -> Self {
        let mut gens = Vec::new();
        // S_n is generated by adjacent transpositions
        for i in 0..n.saturating_sub(1) {
            let mut p: Vec<usize> = (0..n).collect();
            p.swap(i, i + 1);
            gens.push(p);
        }
        Self {
            n,
            generators: gens,
            description: format!("Full symmetric group S_{}", n),
        }
    }

    /// Cyclic group Z_n.
    pub fn cyclic(n: usize) -> Self {
        let mut p: Vec<usize> = (0..n).collect();
        let first = p.remove(0);
        p.push(first);
        Self {
            n,
            generators: vec![p],
            description: format!("Cyclic group Z_{}", n),
        }
    }

    /// The size of the group (approximate via closure of generators).
    pub fn order(&self) -> usize {
        let n = self.n;
        if n > 8 {
            // Too large to enumerate fully
            return 0;
        }
        let mut elements: HashSet<Vec<usize>> = HashSet::new();
        elements.insert((0..n).collect());
        let mut changed = true;
        while changed {
            changed = false;
            let current: Vec<Vec<usize>> = elements.iter().cloned().collect();
            for p in &current {
                for g in &self.generators {
                    let composed = compose_perm(p, g);
                    if !elements.contains(&composed) {
                        elements.insert(composed);
                        changed = true;
                    }
                }
            }
        }
        elements.len()
    }

    /// Check if a specific permutation is in the group.
    pub fn contains(&self, perm: &[usize]) -> bool {
        if perm.len() != self.n {
            return false;
        }
        let n = self.n;
        if n > 8 {
            // For large n, just check against generators
            return self.generators.iter().any(|g| g == perm);
        }

        let mut elements: HashSet<Vec<usize>> = HashSet::new();
        elements.insert((0..n).collect());
        let mut changed = true;
        while changed {
            changed = false;
            let current: Vec<Vec<usize>> = elements.iter().cloned().collect();
            for p in &current {
                for g in &self.generators {
                    let composed = compose_perm(p, g);
                    if !elements.contains(&composed) {
                        elements.insert(composed);
                        changed = true;
                    }
                }
            }
            if elements.contains(perm) {
                return true;
            }
        }
        elements.contains(perm)
    }

    /// Is this the full symmetric group?
    pub fn is_full_symmetric(&self) -> bool {
        let n = self.n;
        if n > 8 {
            return false;
        }
        let full_order = factorial(n);
        self.order() == full_order
    }
}

fn compose_perm(a: &[usize], b: &[usize]) -> Vec<usize> {
    a.iter().map(|&i| b[i]).collect()
}

fn factorial(n: usize) -> usize {
    (1..=n).product()
}

/// Identify the symmetry group of a multi-agent update rule.
/// Tests which permutations of agent IDs leave the update result invariant.
pub fn identify_symmetry(
    rule: fn(&AgentId, &AgentState, &WorldState) -> AgentState,
    ws: &WorldState,
    tolerance: f64,
) -> SymmetryGroup {
    let update = MultiAgentUpdate::new(rule);
    let base_result = update.apply(ws);

    let n = ws.len();
    if n <= 1 {
        return SymmetryGroup::full_symmetric(n);
    }

    let ids: Vec<AgentId> = ws.ordered_agents().into_iter().cloned().collect();

    // Generate all permutations for small n
    let all_perms = if n <= 8 {
        generate_all_permutations(n)
    } else {
        // For large n, test a sample
        generate_sample_permutations(n)
    };

    let mut invariant_perms: Vec<Vec<usize>> = Vec::new();

    for perm in &all_perms {
        let permuted_ws = ws.permute(perm);
        let permuted_result = update.apply(&permuted_ws);

        // Compare: the result should be the same up to permutation
        // i.e., agent i in the permuted result should have the same state as agent perm[i] in original
        let mut is_invariant = true;
        for (idx, id) in ids.iter().enumerate() {
            if let Some(result_state) = permuted_result.get(id) {
                // The result for agent at position idx should equal the base result for agent at position perm[idx]
                let base_id = &ids[*perm.get(idx).unwrap_or(&idx)];
                if let Some(base_state) = base_result.get(base_id) {
                    for (rv, bv) in result_state.values.iter().zip(base_state.values.iter()) {
                        if (rv - bv).abs() > tolerance {
                            is_invariant = false;
                            break;
                        }
                    }
                }
                if !is_invariant {
                    break;
                }
            }
        }

        if is_invariant {
            invariant_perms.push(perm.clone());
        }
    }

    let description = if invariant_perms.len() == all_perms.len() {
        format!("Full symmetric group S_{}", n)
    } else if invariant_perms.len() == 1 {
        format!("Trivial group on {} elements", n)
    } else {
        format!("Subgroup of S_{} with {} elements", n, invariant_perms.len())
    };

    // Find generators (use adjacent transpositions that are in the group)
    let mut generators = vec![(0..n).collect()]; // identity
    for perm in &invariant_perms {
        if *perm != (0..n).collect::<Vec<_>>() {
            generators.push(perm.clone());
            if generators.len() > n {
                break;
            }
        }
    }

    SymmetryGroup {
        n,
        generators,
        description,
    }
}

fn generate_all_permutations(n: usize) -> Vec<Vec<usize>> {
    let mut perms = Vec::new();
    let mut p: Vec<usize> = (0..n).collect();
    perms.push(p.clone());

    if n <= 1 {
        return perms;
    }

    loop {
        // Next permutation (lexicographic)
        let mut i = n - 1;
        while i > 0 && p[i - 1] >= p[i] {
            i -= 1;
        }
        if i == 0 {
            break;
        }
        let mut j = n - 1;
        while p[j] <= p[i - 1] {
            j -= 1;
        }
        p.swap(i - 1, j);
        p[i..].reverse();
        perms.push(p.clone());
    }
    perms
}

fn generate_sample_permutations(n: usize) -> Vec<Vec<usize>> {
    let mut result = vec![(0..n).collect()];
    // Identity, swap first two, reverse
    let mut p: Vec<usize> = (0..n).collect();
    p.swap(0, 1);
    result.push(p);
    let mut p: Vec<usize> = (0..n).collect();
    p.reverse();
    result.push(p);
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_world() -> WorldState {
        WorldState::new()
            .with(AgentId::new("a"), AgentState::scalar(1.0))
            .with(AgentId::new("b"), AgentState::scalar(2.0))
            .with(AgentId::new("c"), AgentState::scalar(3.0))
    }

    #[test]
    fn test_trivial_group() {
        let g = SymmetryGroup::trivial(3);
        assert_eq!(g.order(), 1);
    }

    #[test]
    fn test_full_symmetric_group() {
        let g = SymmetryGroup::full_symmetric(3);
        assert_eq!(g.order(), 6);
        assert!(g.is_full_symmetric());
    }

    #[test]
    fn test_cyclic_group() {
        let g = SymmetryGroup::cyclic(4);
        assert_eq!(g.order(), 4);
    }

    #[test]
    fn test_contains_identity() {
        let g = SymmetryGroup::full_symmetric(3);
        assert!(g.contains(&[0, 1, 2]));
    }

    #[test]
    fn test_contains_swap() {
        let g = SymmetryGroup::full_symmetric(3);
        assert!(g.contains(&[1, 0, 2]));
    }

    #[test]
    fn test_averaging_full_symmetry() {
        let ws = sample_world();
        let group = identify_symmetry(crate::agent::averaging_rule, &ws, 1e-10);
        // Averaging is permutation-invariant → full symmetric
        assert_eq!(group.n, 3);
    }

    #[test]
    fn test_max_full_symmetry() {
        let ws = sample_world();
        let group = identify_symmetry(crate::agent::max_rule, &ws, 1e-10);
        assert_eq!(group.n, 3);
    }

    #[test]
    fn test_leader_rule_not_full_symmetry() {
        let ws = sample_world();
        let group = identify_symmetry(crate::agent::leader_rule, &ws, 1e-10);
        // Leader rule breaks permutation symmetry
        // Should not be full symmetric (fewer invariant permutations)
        assert!(group.generators.len() < 6 || !group.is_full_symmetric());
    }

    #[test]
    fn test_group_description() {
        let g = SymmetryGroup::full_symmetric(4);
        assert!(g.description.contains("S_4"));
    }

    #[test]
    fn test_factorial() {
        assert_eq!(factorial(1), 1);
        assert_eq!(factorial(3), 6);
        assert_eq!(factorial(5), 120);
    }

    #[test]
    fn test_generate_all_permutations() {
        let perms = generate_all_permutations(3);
        assert_eq!(perms.len(), 6);
        // Each permutation should be unique
        let set: std::collections::HashSet<Vec<usize>> = perms.iter().cloned().collect();
        assert_eq!(set.len(), 6);
    }

    #[test]
    fn test_compose_perm() {
        let a = vec![1, 0, 2];
        let b = vec![2, 1, 0];
        let c = compose_perm(&a, &b);
        assert_eq!(c, vec![1, 2, 0]);
    }
}
